### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by random-robbie** [prjblk/wordpress-audit-automation#2]
Hey,

I've tried mysql 5.7 and 8.0 and keep getting the following issue.

```
python3 wordpress-plugin-audit.py --create-schema --audit
Auditing plugins:   0%|                                                                                                                                                                                               | 0/104 [00:00<?, ?it/s]
┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

Auditing plugins:   1%|█▊                                                                                                                                                                                     | 1/104 [00:05<09:35,  5.59s/it]
┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

Auditing plugins:   2%|███▌                                                                                                                                                                                   | 2/104 [00:07<06:01,  3.55s/it]
┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

Auditing plugins:   2%|███▌                                                                                                                                                                                   | 2/104 [00:10<09:16,  5.45s/it]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 555, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`PluginResults`, CONSTRAINT `PluginResults_ibfk_1` FOREIGN KEY (`slug`) REFERENCES `PluginData` (`slug`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rwiggins/tools/wordpress-audit-automation/wordpress-plugin-audit.py", line 199, in <module>
    run_semgrep_and_store_results(
  File "/Users/rwiggins/tools/wordpress-audit-automation/wordpress-plugin-audit.py", line 136, in run_semgrep_and_store_results
    insert_result_into_db(cursor, plugin, item)
  File "/Users/rwiggins/tools/wordpress-audit-automation/dbutils.py", line 136, in insert_result_into_db
    cursor.execute(sql, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 276, in execute
    result = self._cnx.cmd_query(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 563, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`PluginResults`, CONSTRAINT `PluginResults_ibfk_1` FOREIGN KEY (`slug`) REFERENCES `PluginData` (`slug`))
```

any suggestions?

**Comment by random-robbie** [comment]
Closing as i might have an idea of what it is.

**Comment by random-robbie** [comment]
Reopen - Still having issues with this from a fresh install. Tried using docker mysql:latest and 5.7 and just done a fresh vm of ubuntu 22.04 and got same issue.

**Comment by random-robbie** [comment]
Just tried with importing your audit.sql and then trying to reaudit and it's done the same.

**Comment by random-robbie** [comment]
ran in to a few issues and fixed them. will do a fork at a later date with the updated version.
even had an issue of having to put longtext in for the vuln_lines colum.

**Comment by eddiez9** [comment]
> _mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`wordpress`.`PluginResults`, CONSTRAINT `PluginResults_ibfk_1` FOREIGN KEY (`slug`) REFERENCES `PluginData` (`slug`))

Hi there, 

The error in your snippet suggests that the plugin slug you're trying to audit does not exist in the PluginData table.

Can you check if you downloaded the plugins correctly with --download to ensure that the relevant row in PluginData is created.

**Comment by random-robbie** [comment]
Hey,

This was correct the plugin for what ever reason was unable to be downloaded.

I'm going to close this out as fixed. thanks for the response!
